version: 2
jobs:
  build:
    steps:
      - checkout
      - run
          name: build stage
          command: echo "Bulding..."
  test:
    steps:
      - checkout
      - run
          name: test stage
          command: echo "Testing..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test