version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: build
          command: echo "building..."

  test:
    steps:
      - checkout
      - run:
          command: echo "testing..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test